# Generated by Django 5.0.14 on 2025-04-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
    ]
