# Generated by Django 5.0.14 on 2025-04-23 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantacallao',
            name='detalle',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
