# Generated by Django 5.0.14 on 2025-04-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='nombre',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
