# Generated by Django 5.0.14 on 2025-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0002_remove_proyecto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_gasto',
            field=models.CharField(choices=[('Por separado', 'Por separado'), ('A todo costo', 'A todo costo')], max_length=20),
        ),
    ]
