# Generated by Django 5.0.14 on 2025-04-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0003_alter_proyecto_tipo_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='codigo_proyecto',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
    ]
