# Generated by Django 5.0.14 on 2025-04-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0003_gastogeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='gastos')),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
