# Generated by Django 5.0.14 on 2025-04-20 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0004_rename_codigo_proyecto_proyecto_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='centro_de_costos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro_costos.centrodecostos'),
        ),
    ]
