# Generated by Django 5.0.14 on 2025-04-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0005_nuevogasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevogasto',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='monto_dolares',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='monto_soles',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='nuevogasto',
            name='tipo_gasto',
        ),
        migrations.AddField(
            model_name='nuevogasto',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nuevogasto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
