# Generated by Django 5.0.14 on 2025-04-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_costos', '0007_gaston1_gaston2_gaston3'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevogasto',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
