# Generated by Django 5.0.14 on 2025-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='partida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
