# Generated by Django 5.0.14 on 2025-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='partidas'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='planos_y_otros'),
        ),
    ]
