# Generated by Django 5.2 on 2025-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Estandar'), (2, 'Legal'), (3, 'Administrador')], null=True),
        ),
    ]
