# Generated by Django 5.2 on 2025-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('partida', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('pg', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro_costos', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documentos/partidas')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('pg', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro_costos', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documentos/planos')),
            ],
        ),
    ]
