# Generated by Django 5.2 on 2025-04-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0003_partida_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='costo',
            field=models.CharField(max_length=100),
        ),
    ]
