# Generated by Django 5.2 on 2025-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0004_alter_partida_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='costo',
            field=models.CharField(max_length=100),
        ),
    ]
