# Generated by Django 5.0.14 on 2025-04-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0005_alter_plano_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/planos_y_otros'),
        ),
    ]
