# Generated by Django 5.0.14 on 2025-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0006_alter_plano_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
