# Generated by Django 5.0.14 on 2025-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas_planos', '0007_alter_partida_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/partidas'),
        ),
    ]
